const productos = [
    // ===== MUJER (5) =====
    {
        id: 1,
        nombre: "Pijama Seda Rosada",
        precio: "$75.000",
        categoria: "mujer",
        descripcion: "Tela de seda suave, escote en V, manga larga. Perfecta para noches especiales.",
        imagenes: ["img/productos/pijama-seda-rosada.jpg", "img/productos/pijama-seda-rosada2.jpg"],
        tallas: ["S", "M", "L"],
        colores: ["Rosado", "Blanco"],
        nuevo: true,
        destacado: true,
        agotado: false,
        stock: 5,
        whatsapp: "Hola, quiero la Pijama Seda Rosada"
    },
    {
        id: 2,
        nombre: "Pijama Algodón Estampado",
        precio: "$60.000",
        categoria: "mujer",
        descripcion: "Algodón 100% con estampado de lunares. Cómoda y fresca.",
        imagenes: ["img/productos/mujer-estampada.jpg", "img/productos/mujer-estampada2.jpg"],
        tallas: ["S", "M", "L"],
        colores: ["Blanco/Negro"],
        nuevo: false,
        destacado: false,
        agotado: false,
        stock: 8,
        whatsapp: "Hola, quiero la Pijama Algodón Estampado"
    },
    {
        id: 3,
        nombre: "Pijama Encaje Negro",
        precio: "$85.000",
        categoria: "mujer",
        descripcion: "Elegante pijama con detalles de encaje en escote y mangas. Ideal para ocasiones especiales.",
        imagenes: ["img/productos/pijama-encaje-negro.jpg", "img/productos/pijama-encaje-negro2.jpg"],
        tallas: ["S", "M"],
        colores: ["Negro"],
        nuevo: true,
        destacado: true,
        agotado: false,
        stock: 2,
        whatsapp: "Hola, quiero la Pijama Encaje Negro"
    },
    {
        id: 4,
        nombre: "Pijama Térmica Invierno",
        precio: "$95.000",
        categoria: "mujer",
        descripcion: "Pijama térmica de felpa, ideal para noches frías. Suave y calentita.",
        imagenes: ["img/productos/pijama-termica.jpg", "img/productos/pijama-termica2.jpg"],
        tallas: ["M", "L", "XL"],
        colores: ["Gris", "Azul marino"],
        nuevo: false,
        destacado: false,
        agotado: true,
        stock: 0,
        whatsapp: "Hola, quiero la Pijama Térmica Invierno"
    },
    {
        id: 5,
        nombre: "Pijama Verano Lino",
        precio: "$70.000",
        categoria: "mujer",
        descripcion: "Pijama de lino fresco, perfecta para climas cálidos. Manga corta y pantalón corto.",
        imagenes: ["img/productos/pijama-lino.jpg", "img/productos/pijama-lino2.jpg"],
        tallas: ["S", "M", "L"],
        colores: ["Beige", "Blanco"],
        nuevo: false,
        destacado: false,
        agotado: false,
        stock: 6,
        whatsapp: "Hola, quiero la Pijama Verano Lino"
    },
    // ===== HOMBRE (4) =====
    {
        id: 6,
        nombre: "Pijama Hombre Clásico",
        precio: "$70.000",
        categoria: "hombre",
        descripcion: "Camisa y pantalón de algodón, corte relajado. Colores neutros.",
        imagenes: ["img/productos/pijama-clasica-hombre.jpg", "img/productos/pijama-clasica-hombre2.jpg"],
        tallas: ["S", "M", "L", "XL"],
        colores: ["Azul marino", "Gris"],
        nuevo: false,
        destacado: true,
        agotado: false,
        stock: 4,
        whatsapp: "Hola, quiero la Pijama Hombre Clásico"
    },
    {
        id: 7,
        nombre: "Pijama Hombre con Estampado",
        precio: "$68.000",
        categoria: "hombre",
        descripcion: "Estampado de cuadros, botones frontales. 100% algodón.",
        imagenes: ["img/productos/pijama-estampado-hombre.jpg", "img/productos/pijama-estampado-hombre2.jpg"],
        tallas: ["M", "L", "XL"],
        colores: ["Rojo/Cuadros"],
        nuevo: true,
        destacado: false,
        agotado: false,
        stock: 7,
        whatsapp: "Hola, quiero la Pijama Hombre con Estampado"
    },
    {
        id: 8,
        nombre: "Pijama Hombre Seda",
        precio: "$90.000",
        categoria: "hombre",
        descripcion: "Pijama de seda con botonadura y cuello clásico. Elegancia y confort.",
        imagenes: ["img/productos/pijama-seda-hombre.jpg", "img/productos/pijama-seda-hombre2.jpg"],
        tallas: ["M", "L"],
        colores: ["Negro", "Azul"],
        nuevo: true,
        destacado: false,
        agotado: false,
        stock: 3,
        whatsapp: "Hola, quiero la Pijama Hombre Seda"
    },
    {
        id: 9,
        nombre: "Pijama Hombre Térmico",
        precio: "$80.000",
        categoria: "hombre",
        descripcion: "Pijama térmico de algodón, perfecto para el invierno.",
        imagenes: ["img/productos/pijama-termica-hombre.jpg", "img/productos/pijama-termica-hombre2.jpg"],
        tallas: ["L", "XL"],
        colores: ["Gris oscuro"],
        nuevo: false,
        destacado: false,
        agotado: true,
        stock: 0,
        whatsapp: "Hola, quiero la Pijama Hombre Térmico"
    },
    // ===== NIÑOS (4) =====
    {
        id: 10,
        nombre: "Pijama Niño Dinosaurio",
        precio: "$45.000",
        categoria: "ninos",
        descripcion: "Pijama de algodón con estampado de dinosaurios. Manga larga y pantalón.",
        imagenes: ["img/productos/pijama-dino.jpg", "img/productos/pijama-dino2.jpg"],
        tallas: ["4", "6", "8", "10"],
        colores: ["Verde", "Azul"],
        nuevo: true,
        destacado: true,
        agotado: false,
        stock: 10,
        whatsapp: "Hola, quiero la Pijama Niño Dinosaurio"
    },
    {
        id: 11,
        nombre: "Pijama Niña Unicornio",
        precio: "$45.000",
        categoria: "ninos",
        descripcion: "Pijama de algodón con unicornios y brillos. Ideal para soñar.",
        imagenes: ["img/productos/pijama-unicornio-nina.jpg", "img/productos/pijama-unicornio-nina2.jpg"],
        tallas: ["4", "6", "8", "10"],
        colores: ["Rosado", "Blanco"],
        nuevo: false,
        destacado: false,
        agotado: false,
        stock: 6,
        whatsapp: "Hola, quiero la Pijama Niña Unicornio"
    },
    {
        id: 12,
        nombre: "Pijama Niño Espacial",
        precio: "$48.000",
        categoria: "ninos",
        descripcion: "Pijama con estampado de cohetes y planetas. Algodón suave.",
        imagenes: ["img/productos/pijama-espacio.jpg", "img/productos/pijama-espacio2.jpg"],
        tallas: ["6", "8", "10", "12"],
        colores: ["Azul", "Negro"],
        nuevo: true,
        destacado: false,
        agotado: false,
        stock: 4,
        whatsapp: "Hola, quiero la Pijama Niño Espacial"
    },
    {
        id: 13,
        nombre: "Pijama Niña Princesa",
        precio: "$50.000",
        categoria: "ninos",
        descripcion: "Pijama con volantes y estampado de princesas. Tejido suave.",
        imagenes: ["img/productos/pijama-princesa.jpg", "img/productos/pijama-princesa2.jpg"],
        tallas: ["4", "6", "8"],
        colores: ["Rosado", "Lila"],
        nuevo: false,
        destacado: false,
        agotado: true,
        stock: 0,
        whatsapp: "Hola, quiero la Pijama Niña Princesa"
    },
    // ===== PAREJAS (3) =====
    {
        id: 14,
        nombre: "Conjunto Pareja Corazones",
        precio: "$130.000",
        categoria: "parejas",
        descripcion: "Set de 2 pijamas (ella y él) con estampado de corazones. Incluye bolsa de regalo.",
        imagenes: ["img/productos/conjunto-corazones.jpg", "img/productos/conjunto-corazones2.jpg"],
        tallas: ["Ella S-M", "Él M-L"],
        colores: ["Rojo/Blanco"],
        nuevo: true,
        destacado: true,
        agotado: false,
        stock: 3,
        whatsapp: "Hola, quiero el Conjunto Pareja Corazones"
    },
    {
        id: 15,
        nombre: "Conjunto Pareja Lino",
        precio: "$140.000",
        categoria: "parejas",
        descripcion: "Pijamas de lino para él y ella, perfectas para clima cálido.",
        imagenes: ["img/productos/conjunto-lino.jpg", "img/productos/conjunto-lino2.jpg"],
        tallas: ["Ella S-M", "Él M-L"],
        colores: ["Beige", "Blanco"],
        nuevo: false,
        destacado: false,
        agotado: false,
        stock: 4,
        whatsapp: "Hola, quiero el Conjunto Pareja Lino"
    },
    {
        id: 16,
        nombre: "Conjunto Pareja Navideño",
        precio: "$150.000",
        categoria: "parejas",
        descripcion: "Pijamas con estampado navideño, perfectas para las fiestas.",
        imagenes: ["img/productos/conjunto-navidad.jpg", "img/productos/conjunto-navidad2.jpg"],
        tallas: ["Ella M-L", "Él L-XL"],
        colores: ["Rojo/Verde"],
        nuevo: true,
        destacado: true,
        agotado: false,
        stock: 2,
        whatsapp: "Hola, quiero el Conjunto Pareja Navideño"
    }
];